[Rainmeter]
Update=1000
Background=#@#player.png
DynamicWindowSize=1

[MeasurePlayer]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Title

[MeasureNumber]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Number

[MeasureArtist]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Artist

[MeasureTitle]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Title

[MeasureCover]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Cover

[MeasureAlbum]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Album

[MeasureDuration]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Duration

[MeasurePosition]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Position

[MeasureProgress]
Measure=NowPlaying
PlayerName=CAD
PlayerType=Progress

;meter

[MeterNumber]
Meter=String
MeasureName=MeasureNumber
X=170
Y=100
FontColor=255,82,0
FontWeight=500
FontFace=Segoe UI
FontSize=12
AntiAlias=1
Text=%1 :

[MeterTitle]
Meter=String
MeasureName=MeasureTitle
W=275
ClipString=1
X=200
Y=100
FontColor=255,82,0
FontWeight=500
FontFace=Segoe UI
FontSize=12
AntiAlias=1
Text=%1 

[MeterCover]
Meter=Image
MeasureName=MeasureCover
X=4
Y=4
W=130
H=130
PreserveAspectRatio=1

[MeterPiste]
Meter=String
X=170
Y=75
FontColor=255,255,255
FontFace=Segoe UI
FontSize=12
Text="Piste :"

[MeterArtistTitre]
Meter=String
X=175
Y=15
FontColor=255,255,255
FontFace=Segoe UI
FontSize=12
Text="Artiste :"

[MeterArtist]
Meter=String
MeasureName=MeasureArtist
X=172
Y=38
W=146
FontColor=255,82,0
FontWeight=500
FontFace=Segoe UI
FontSize=12
Text=%1

[MeterAlbumTitre]
Meter=String
X=345
Y=15
SolidColor=255,255,255,30
FontColor=255,255,255
FontFace=Segoe UI
FontSize=12
Text="Album :"

[MeterAlbum]
Meter=String
MeasureName=MeasureAlbum
W=138
Y=39
X=340
Y=38
ClipString=1
FontColor=255,82,0
FontWeight=500
FontFace=Segoe UI
FontSize=12

Text=%1

[MeterTime]
Meter=String
MeasureName=MeasurePosition
X=10
Y=160
FontColor=255,82,0
FontFace=Segoe UI
FontSize=12
FontWeight=500
Text=%1

[MeterDuration]
Meter=String
MeasureName=MeasureDuration
X=450
Y=160
FontColor=255,82,0
FontFace=Segoe UI
FontSize=12
FontWeight=500
Text=%1

[MeterProgress]
Meter=Bar
MeasureName=MeasureProgress
X=20
Y=158
W=460
H=4
BarOrientation=Horizontal
BarColor=255,82,11
SolidColor=255,82,11,75

[MeterPlay]
Meter=Button
ButtonImage=#@#play.png
W=20
H=20
X=240
Y=174
LeftMouseUpAction=[!CommandMeasure MeasurePlayer "PlayPause"]

[MeterRetour]
Meter=Button
ButtonImage=#@#retour.png
W=20
H=20
X=210
Y=174
LeftMouseUpAction=[!CommandMeasure MeasurePlayer "Previous"]

[MeterSuivant]
Meter=Button
ButtonImage=#@#suivant.png
W=20
H=20
X=270
Y=174
LeftMouseUpAction=[!CommandMeasure MeasurePlayer "Next"]
