[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
Background=#@#fond_memoire.png


[MeasureChargeMemPhys]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw1
MinValue=0
MaxValue=100

[MeasureChargeMemVirt]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw0
MinValue=0
MaxValue=100

[MeterRoundlineMemPhys]
Meter=Roundline
MeasureName=MeasureChargeMemPhys
x=38
y=32
w=50
h=50
LineStart=25
LineColor=255,67,0
LineLength=12
Solid=1
StartAngle=-4.1887
RotationAngle=5.236

[MeterRoundlineMemVirt]
Meter=Roundline
MeasureName=MeasureChargeMemVirt
x=142
y=32
w=50
h=50
LineStart=25
LineColor=255,67,0,255
LineLength=12
Solid=1
StartAngle=-4.1887
RotationAngle=5.236

[MeterStringVirtPourcent]
Meter=String
x= 142
y=85
FontFace=Arial
FontSize=10
FontColor=255,255,255
;FontWeight=700
Text="Virtuelle"

[MeterStringTitre]
Meter=String
x= 63
y=10
FontFace=Arial
FontSize=10
FontColor=255,255,255
;FontWeight=700
Text="Charge Memoire"

[MeterStringPhysiquePourcent]
Meter=String
x= 38
y=85
FontFace=Arial
FontSize=10
FontColor=255,255,255
;FontWeight=700
Text="Physique"
