[Rainmeter]
Update=1000
;Background=#@#TempCpuFond.png
BackgroundMode=2
SolidColor=0,0,0,100
DynamicWindowSize=1
AccurateText=1
ContextTitle=Display Sensors
ContextAction=[!ActivateConfig "HWiNFO_New\ShowReg" "ShowReg.ini"]

[MeasureTempCpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw18
MinValue=0
MaxValue=100

[MeasureTempGpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw41
MinValue=0
MaxValue=100

;meter

[MeterCpuGpuLine]
Meter=Line
MeasureName=MeasureTempCpu  
MeasureName2=MeasureTempGpu
x=170.5
y=8.8
w=520
h=35
LineCount=2
LineColor=0,190,200,255
LineColor2=242,13,13,255
LineWidth=1
AntiAlias=1
AutoScale=1

[MeterCpuChargeText]
Meter=String
MeasureName=MeasureTempCpu
x=25
y=5
FontSize=12
FontColor=0,190,200,255
FontWeight=700
Text="CPU: %1%"

[MeterGpuChargeText]
Meter=String
MeasureName=MeasureTempGpu
x=25
y=25
FontSize=12
FontColor=242,13,13,255
FontWeight=700
Text="GPU: %1%"