[Rainmeter]
Update=1000
Background=#@#DetailsProcesseur.png
DynamicWindowSize=1
AccurateText=1
ContextTitle=Display Sensors
ContextAction=[!ActivateConfig "HWiNFO_New\ShowReg" "ShowReg.ini"]

[MeasureHorlogeCoeur]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw17

[MeasureChargeCore0T0]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw3
MinValue=0
MaxValue=100

[MeasureChargeCore0T1]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw4
MinValue=0
MaxValue=100

[MeasureChargeCore1T0]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw5
MinValue=0
MaxValue=100

[MeasureChargeCore1T1]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw6
MinValue=0
MaxValue=100

[MeasureChargeCore2T0]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw7
MinValue=0
MaxValue=100

[MeasureChargeCore2T1]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw8
MinValue=0
MaxValue=100

[MeasureChargeCore3T0]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw9
MinValue=0
MaxValue=100

[MeasureChargeCore3T1]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw10
MinValue=0
MaxValue=100

[MeasureChargeCore4T0]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw11
MinValue=0
MaxValue=100

[MeasureChargeCore4T1]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw12
MinValue=0
MaxValue=100

[MeasureChargeCore5T0]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw13
MinValue=0
MaxValue=100

[MeasureChargeCore5T1]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw14
MinValue=0
MaxValue=100

[MeasureConsoCpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw20


;meter

[MeterChargeCore0T0]
Meter=Bar
MeasureName=MeasureChargeCore0T0
w=100
h=10
x=50
y=30
BarColor=0,22,255,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore0T0]
Meter=String
x=10
y=27
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C0T0"

[MeterChargeCore0T0Pourcentage]
Meter=String
MeasureName=MeasureChargeCore0T0
x=160
y=27
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore0T1]
Meter=Bar
MeasureName=MeasureChargeCore0T1
w=100
h=10
x=50
y=50
BarColor=0,118,255,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore0T1]
Meter=String
x=10
y=47
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C0T1"

[MeterChargeCore0T1Pourcentage]
Meter=String
MeasureName=MeasureChargeCore0T1
x=160
y=47
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore1T0]
Meter=Bar
MeasureName=MeasureChargeCore1T0
w=100
h=10
x=50
y=70
BarColor=222,0,0,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore1T0]
Meter=String
x=10
y=67
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C1T0"

[MeterChargeCore1T0Pourcentage]
Meter=String
MeasureName=MeasureChargeCore1T0
x=160
y=67
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterTextCore1T1]
Meter=String
x=10
y=87
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C1T1"

[MeterChargeCore1T1]
Meter=Bar
MeasureName=MeasureChargeCore1T1
w=100
h=10
x=50
y=90
BarColor=193,111,111,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterChargeCore1T1Pourcentage]
Meter=String
MeasureName=MeasureChargeCore1T1
x=160
y=90
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore2T0]
Meter=Bar
MeasureName=MeasureChargeCore2T0
w=100
h=10
x=50
y=110
BarColor=0,255,24,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore2T0]
Meter=String
x=10
y=107
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C2T0"

[MeterChargeCore2T0Pourcentage]
Meter=String
MeasureName=MeasureChargeCore2T0
x=160
y=107
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore2T1]
Meter=Bar
MeasureName=MeasureChargeCore2T1
w=100
h=10
x=50
y=130
BarColor=0,137,13,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore2T1]
Meter=String
x=10
y=127
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C2T1"

[MeterChargeCore2T1Pourcentage]
Meter=String
MeasureName=MeasureChargeCore2T1
x=160
y=127
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore3T0]
Meter=Bar
MeasureName=MeasureChargeCore3T0
w=100
h=10
x=50
y=150
BarColor=255,219,0,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore3T0]
Meter=String
x=10
y=147
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C3T0"

[MeterChargeCore3T0Pourcentage]
Meter=String
MeasureName=MeasureChargeCore3T0
x=160
y=147
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore3T1]
Meter=Bar
MeasureName=MeasureChargeCore3T1
w=100
h=10
x=50
y=170
BarColor=169,153,56,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore3T1]
Meter=String
x=10
y=167
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C3T1"

[MeterChargeCore3T1Pourcentage]
Meter=String
MeasureName=MeasureChargeCore3T1
x=160
y=167
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore4T0]
Meter=Bar
MeasureName=MeasureChargeCore4T0
w=100
h=10
x=50
y=190
BarColor=162,0,255,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore4T0]
Meter=String
x=10
y=187
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C4T0"

[MeterChargeCore4T0Pourcentage]
Meter=String
MeasureName=MeasureChargeCore4T0
x=160
y=187
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore4T1]
Meter=Bar
MeasureName=MeasureChargeCore4T1
w=100
h=10
x=50
y=210
BarColor=69,21,97,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore4T1]
Meter=String
x=10
y=207
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C4T1"

[MeterChargeCore4T1Pourcentage]
Meter=String
MeasureName=MeasureChargeCore4T1
x=160
y=207
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore5T0]
Meter=Bar
MeasureName=MeasureChargeCore5T0
w=100
h=10
x=50
y=230
BarColor=0,255,218,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore5T0]
Meter=String
x=10
y=227
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C5T0"

[MeterChargeCore5T0Pourcentage]
Meter=String
MeasureName=MeasureChargeCore5T0
x=160
y=227
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterChargeCore5T1]
Meter=Bar
MeasureName=MeasureChargeCore5T1
w=100
h=10
x=50
y=250
BarColor=38,163,145,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTextCore5T1]
Meter=String
x=10
y=247
FontSize=10
FontWeight=700
FontColor=0,0,0,255
Text="C5T1"

[MeterChargeCore5T1Pourcentage]
Meter=String
MeasureName=MeasureChargeCore5T1
x=160
y=247
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text=%1%

[MeterLineCharge]
Meter=Line
MeasureName=MeasureChargeCore0T0
MeasureName2=MeasureChargeCore0T1
MeasureName3=MeasureChargeCore1T0
MeasureName4=MeasureChargeCore1T1
MeasureName5=MeasureChargeCore2T0
MeasureName6=MeasureChargeCore2T1
MeasureName7=MeasureChargeCore3T0
MeasureName8=MeasureChargeCore3T1
MeasureName9=MeasureChargeCore4T0
MeasureName10=MeasureChargeCore4T1
MeasureName11=MeasureChargeCore5T0
MeasureName12=MeasureChargeCore5T1
w=337
h=188
x=258    
y=34
LineColor=0,22,255,255
LineColor2=0,118,255,255
LineColor3=222,0,0,255
LineColor4=193,111,111,255
LineColor5=0,255,24,255
LineColor6=0,137,13,255
LineColor7=255,219,0,255
LineColor8=169,153,56,255
LineColor9=162,0,255,255
LineColor10=69,21,97,255
LineColor11=0,255,218,255
LineColor12=38,163,145,255
SolidColor=0,0,0,175
LineCount=12
LineWidth=1
AutoScale=1
AntiAlias=1
start=0,0
end=100,100

[MeterHorlogeCoeur]
MeasureName=MeasureHorlogeCoeur
Meter=String
FontSize=12
x=20
y=300
fontColor=0,0,0,255
StringStyle=Bold
Text="Frequence: %1MHz"

[MeterLineHorlogeCpu]
Meter=Line
MeasureName=MeasureHorlogeCoeur
w=200
h=50
x=10
y=320
LineColor=255,196,3,255
SolidColor=0,0,0,175
LineWidth=1
AutoScale=1
AntiAlias=1

[MeterTextConso]
Meter=String
MeasureName=MeasureConsoCpu
x=300
y=300
FontSize=12
FontWeight=700
FontColor=0,0,0,255
Text="Consommation: %1W"

[MeterLineConsoCpu]
Meter=Line
MeasureName=MeasureConsoCpu
x=300
y=320
w=200
h=50
LineColor=255,196,3,255
SolidColor=0,0,0,175
LineWidth=1
AutoScale=1
AntiAlias=1

