[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1

;measures C:

[MeasureTotalDiskSpaceC]
Measure=FreeDiskSpace
Drive=C:
Total=1

[MeasureTotalDiskSpaceC_GB]
Measure=Calc
Formula=Round(MeasureTotalDiskSpaceC/ 1073741824)

[MeasureUsedDiskSpaceC]
Measure=FreeDiskSpace
Drive=C:

[MeasureUsedDiskSpaceBarC]
Measure=FreeDiskSpace
Drive=C:
InvertMeasure=1

[MeasureUsedDiskSpaceC_GB]
Measure=Calc
Formula=Round(MeasureUsedDiskSpaceC/ 1073741824)

[MeasureVieC]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw30
MinValue=0
MaxValue=100

;measures D:

[MeasureTotalDiskSpaceD]
Measure=FreeDiskSpace
Drive=D:
Total=1

[MeasureTotalDiskSpaceD_GB]
Measure=Calc
Formula=Round(MeasureTotalDiskSpaceD/ 1073741824)

[MeasureUsedDiskSpaceD]
Measure=FreeDiskSpace
Drive=D:

[MeasureUsedDiskSpaceBarD]
Measure=FreeDiskSpace
Drive=D:
InvertMeasure=1

[MeasureUsedDiskSpaceD_GB]
Measure=Calc
Formula=Round(MeasureUsedDiskSpaceD/ 1073741824)

;measure E:

[MeasureTotalDiskSpaceE]
Measure=FreeDiskSpace
Drive=E:
Total=1

[MeasureTotalDiskSpaceE_GB]
Measure=Calc
Formula=Round(MeasureTotalDiskSpaceE/ 1073741824)

[MeasureUsedDiskSpaceE]
Measure=FreeDiskSpace
Drive=E:

[MeasureUsedDiskSpaceBarE]
Measure=FreeDiskSpace
Drive=E:
InvertMeasure=1

[MeasureUsedDiskSpaceE_GB]
Measure=Calc
Formula=Round(MeasureUsedDiskSpaceE/ 1073741824)

[MeasureVieE]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw26
MinValue=0
MaxValue=100

;measure H:

[MeasureTotalDiskSpaceH]
Measure=FreeDiskSpace
Drive=H:
Total=1

[MeasureTotalDiskSpaceH_GB]
Measure=Calc
Formula=Round(MeasureTotalDiskSpaceH/ 1073741824)

[MeasureUsedDiskSpaceH]
Measure=FreeDiskSpace
Drive=H:

[MeasureUsedDiskSpaceBarH]
Measure=FreeDiskSpace
Drive=H:
InvertMeasure=1

[MeasureUsedDiskSpaceH_GB]
Measure=Calc
Formula=Round(MeasureUsedDiskSpaceH/ 1073741824)

[MeasureVieH]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw28
MinValue=0
MaxValue=100

;Measure Temperatures

[MeasureTempC]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw29

[MeasureTempD]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw24

[MeasureTempE]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw25

[MeasureTempH]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw27




;meter

[Background]
Meter=Image
ImageName=#@#HDD.png

[MeterCString]
Meter=String
x= 20
y= 20
FontFace=Arial
FontSize=12
FontColor=255,255,255
FontWeight=700
Text="C:"

[MeterRatioDiskSpaceC]
Meter=String
x= 20
y= 40
FontFace=Arial
FontSize=10
FontColor=255,255,255
MeasureName=MeasureTotalDiskSpaceC_GB
MeasureName2=MeasureUsedDiskSpaceC_GB
Text="%2 Go libres sur %1 Go"


[MeterRatioBarSpaceC]
Meter=Bar
MeasureName=MeasureUsedDiskSpaceBarC
x= 20
y= 65
W=150
H=10
BarOrientation=Horizontal
BarColor=255,67,0,255
SolidColor=255,67,0,100

[MeterStringVie]
Meter=String
x= 20
y= 85
FontFace=Arial
FontSize=10
FontColor=255,255,255
Text="Durée de vie:"

[MeterVieC]
Meter=Bar
MeasureName=MeasureVieC
x=20
y=105
W=150
H=10
BarOrientation=Horizontal
BarImage=#@#Images\barreVie.png
SolidColor=0,0,0,100

[MeterVieCPercent]
Meter=String
MeasureName=MeasureVieC
x= 20
y= 125
FontFace=Arial
FontSize=10
FontColor=255,255,255
Text="%1%"



[MeterDString]
Meter=String
x= 220
y= 20
FontFace=Arial
FontSize=12
FontColor=255,255,255
FontWeight=700
Text="D:"

[MeterRatioDiskSpaceD]
Meter=String
x= 220
y= 40
FontFace=Arial
FontSize=10
FontColor=255,255,255
MeasureName=MeasureTotalDiskSpaceD_GB
MeasureName2=MeasureUsedDiskSpaceD_GB
Text="%2 Go libres sur %1 Go"


[MeterRatioBarSpaceD]
Meter=Bar
MeasureName=MeasureUsedDiskSpaceBarD
x= 220
y= 65
W=150
H=10
BarOrientation=Horizontal
BarColor=255,67,0,255
SolidColor=255,67,0,100

[MeterEString]
Meter=String
x= 20
y= 180
FontFace=Arial
FontSize=12
FontColor=255,255,255
FontWeight=700
Text="E:"

[MeterRatioDiskSpaceE]
Meter=String
x= 20
y= 200
FontFace=Arial
FontSize=10
FontColor=255,255,255
MeasureName=MeasureTotalDiskSpaceE_GB
MeasureName2=MeasureUsedDiskSpaceE_GB
Text="%2 Go libres sur %1 Go"


[MeterRatioBarSpaceE]
Meter=Bar
MeasureName=MeasureUsedDiskSpaceBarE
x= 20
y= 225
W=150
H=10
BarOrientation=Horizontal
BarColor=255,67,0,255
SolidColor=255,67,0,100

[MeterStringVieE]
Meter=String
x= 20
y= 245
FontFace=Arial
FontSize=10
FontColor=255,255,255
Text="Durée de vie:"

[MeterVieE]
Meter=Bar
MeasureName=MeasureVieE
x=20
y=265
W=150
H=10
BarOrientation=Horizontal
BarImage=#@#Images\barreVie.png
SolidColor=0,0,0,100

[MeterVieEPercent]
Meter=String
MeasureName=MeasureVieE
x= 20
y= 285
FontFace=Arial
FontSize=10
FontColor=255,255,255
Text="%1%"

[MeterHString]
Meter=String
x= 220
y= 180
FontFace=Arial
FontSize=12
FontColor=255,255,255
FontWeight=700
Text="H:"

[MeterRatioDiskSpaceH]
Meter=String
x= 220
y= 200
FontFace=Arial
FontSize=10
FontColor=255,255,255
MeasureName=MeasureTotalDiskSpaceH_GB
MeasureName2=MeasureUsedDiskSpaceH_GB
Text="%2 Go libres sur %1 Go"


[MeterRatioBarSpaceH]
Meter=Bar
MeasureName=MeasureUsedDiskSpaceBarH
x= 220
y= 225
W=150
H=10
BarOrientation=Horizontal
BarColor=255,67,0,255
SolidColor=255,67,0,100

[MeterStringVieH]
Meter=String
x= 220
y= 245
FontFace=Arial
FontSize=10
FontColor=255,255,255
Text="Durée de vie:"

[MeterVieH]
Meter=Bar
MeasureName=MeasureVieH
x=220
y=265
W=150
H=10
BarOrientation=Horizontal
BarImage=#@#Images\barreVie.png
SolidColor=0,0,0,100

[MeterVieHPercent]
Meter=String
MeasureName=MeasureVieH
x= 280
y= 280
FontFace=Arial
FontSize=10
FontColor=255,255,255
Text="%1%"

[MeterTitreTemp]
Meter=String
x= 150
y= 300
FontFace=Arial
FontSize=12
FontColor=255,255,255
FontWeight=700
Text="Température:"

[MeterGraphTemp]
Meter=Line
MeasureName=MeasureTempC
MeasureName2=MeasureTempD
MeasureName3=MeasureTempE
MeasureName4=MeasureTempH
x=10
y=320
W=360
H=100
LineCount=4
LineColor=255,0,0,255
LineColor2=0,0,255,255
LineColor3=0,255,0,255
LineColor4=255,255,0,255
SolidColor=255,255,255,100
LineWidth=1
Autoscale=1

[MeterLegendImageC]
Meter=Image
W=10
H=5
x=10
y=440
SolidColor=255,0,0,255

[MeterLegendRatioC]
Meter=String
MeasureName=MeasureTempC
x=25
y=435
FontFace=Arial
FontSize=12
FontWeight=500
FontColor=255,255,255
Text="C: %1 °C"

[MeterLegendImageD]
Meter=Image
W=10
H=5
x=100
y=440
SolidColor=0,0,255,255

[MeterLegendRatioD]
Meter=String
MeasureName=MeasureTempD
x=115
y=435
FontFace=Arial
FontSize=12
FontWeight=500
FontColor=255,255,255
Text="D: %1 °C"

[MeterLegendImageE]
Meter=Image
W=10
H=5
x=200
y=440
SolidColor=0,255,0,255

[MeterLegendRatioE]
Meter=String
MeasureName=MeasureTempE
x=215
y=435
FontFace=Arial
FontSize=12
FontWeight=500
FontColor=255,255,255
Text="E: %1 °C"

[MeterLegendImageH]
Meter=Image
W=10
H=5
x=300
y=440
SolidColor=255,255,0,255

[MeterLegendRatioH]
Meter=String
MeasureName=MeasureTempH
x=315
y=435
FontFace=Arial
FontSize=12
FontWeight=500
FontColor=255,255,255
Text="H: %1 °C"
