[Rainmeter]
Update=1000
Background=#@#TempCpuFond.png
DynamicWindowSize=1
AccurateText=1
ContextTitle=Display Sensors
ContextAction=[!ActivateConfig "HWiNFO_New\ShowReg" "ShowReg.ini"]

[Variables]
Deg=°C

[MeasureTempCpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw19
MinValue=0
MaxValue=100

[MeasureTempGpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw39
MinValue=0
MaxValue=100

[MeasureThermaLimitCpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw21
MinValue=0
MaxValue=100

[MeasureThermaLimitGpu]
Measure=Registry
RegHKey=HKEY_CURRENT_USER
RegKey=SOFTWARE\HWiNFO64\VSB
RegValue=ValueRaw42
MinValue=0
MaxValue=100



;meter

[MeterTempCpuBar]
MeasureName=MeasureTempCpu
Meter=Bar
w=300
h=10
x=25
y=30
BarColor=0,190,200,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterGpuBar]
MeasureName=MeasureTempGpu
Meter=Bar
w=300
h=10
x=350
y=30
BarColor=242,13,13,255
SolidColor=0,0,0,100
BarOrientation=Horizontal

[MeterTempCpuText]
MeasureName=MeasureTempCpu
Meter=String
FontSize=12
x=25
y=5
NumOfDecimals=0
FontColor=255,255,255,175
FontWeight=700
Text=CPU Temperature: %1#Deg#

;[MeterTempCpuLimitText]
;MeasureName=MeasureThermaLimitCpu
;Meter=String
;FontSize=10
;x=250
;y=5
;NumOfDecimals=0
;FontColor=255,255,255,175
;FontWeight=700
;Text=Limit: %1%

[MeterTempGpuText]
MeasureName=MeasureTempGpu
Meter=String
FontSize=12
x=350
y=5
NumOfDecimals=0
FontColor=255,255,255,175
FontWeight=700
Text=GPU Temperature: %1#Deg#

;[MeterTempGpuLimitText]
;MeasureName=MeasureThermaLimitGpu
;Meter=String
;FontSize=10
;x=580
;y=5
;NumOfDecimals=0
;FontColor=255,255,255,175
;ontWeight=700
;Text=Limit: %1%

[MeterTempGraphTitre]
Meter=String
FontSize=12
X=190
Y=45
FontColor=255,255,255,175
FontWeight=700
Text=Temperature Graph

[MeterTempGraph]
Meter=Line
MeasureName=MeasureTempCpu
MeasureName2=MeasureTempGpu
X=25
Y=70
W=500
H=100
LineColor=0,190,200,255
LineColor2=242,13,13,255
SolidColor=0,0,0,50
LineWidth=1
LineCount=2
HorizontalLines=1

[MeterLimitGraphTitre]
Meter=String
FontSize=12
X=580
Y=45
FontColor=255,255,255,175
FontWeight=700
Text=Limit 

[MeterCpuLimiTitre]
Meter=String
FontSize=8
X=555
Y=70
FontColor=255,255,255,175
FontWeight=700
Text=CPU 

[MeterLimitCpuBar]
Meter=Bar
MeasureName=MeasureThermaLimitCpu
X=540
Y=100
W=50
H=70
BarColor=0,190,200,255
SolidColor=0,0,0,50
BarOrientation=Vertical
;LineColor2=242,13,13,255

[MeterGpuLimiTitre]
Meter=String
FontSize=8
X=625
Y=70
FontColor=255,255,255,175
FontWeight=700
Text=GPU 

[MeterLimitGpuBar]
Meter=Bar
MeasureName=MeasureThermaLimitGpu
X=610
Y=100
W=50
H=70
;BarColor=0,190,200,255
SolidColor=0,0,0,50
BarOrientation=Vertical
BarColor=242,13,13,255
