[Rainmeter]
Update=1000
Background=#@#timer.png
DynamicWindowSize=1
AccurateText=1


[MeasureDate]
Measure=Time
Format=%A, %B %#d, %Y

[Measure12HrTime]
Measure=Time
Format=%#I:%M %p

[Measure24HrTimeH]
Measure=Time
Format=%H

[Measure24HrTimeM]
Measure=Time
Format=%M

;meter

[MeterHorloge]
Meter=String
FontWeight=700
MeasureName=Measure12HrTime
MeasureName2=Measure24HrTimeH
MeasureName3=Measure24HrTimeM
FontSize=20
x=10
y=8

fontColor=0,0,0,255
StringStyle=Bold
Text="%2 : %3"