[Rainmeter]
Update=1000
BackgroundMode=2
SolidColor=0,0,0,100

[Metadata]
Name=Mon Skin Meteo
Author=Delphimaster
Information=Un cours simple pour la météo
Version=1.0

[Variables]
;code de ta ville   
LocationCode=6545270
;unité de mesure (m pour métrique, e pour impérial)
Unit=m

[MeasureMeteoParent]
Measure=Plugin
Plugin=WebParser
URL=https://api.openweathermap.org/data/2.5/weather?id=6545270&appid=b6aefe5faf1852b143b7c773a31ed0a4&units=metric&lang=fr
RegEx=(?siU)"temp":"(.*?)","name":"(.*?)"
UpdateRate=1800

[MeasureTemp]
Measure=Plugin
Plugin=WebParser
URL=MeasureMeteoParent
StringIndex=1

[MeasureLocation]
Measure=Plugin
Plugin=WebParser
URL=MeasureMeteoParent
StringIndex=2




;----Styles de police----
[StyleText]
FontFace=Segoe UI
FontColor=255,255,255,255
AntiAlias=1

;----Affichage visuel----



[MeterTemp]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureTemp
X=10
Y=35
w=300
h=50
FontSize=22
Text=%1°C

[MeterLocation]
Meter=String
MeterStyle=StyleText
MeasureName=MeasureLocation
X=10
Y=10
w=300
h=50
FontSize=14
FontWeight=700
Text=ville: %1
